services:
  postgres:
    image: postgres:16.6-alpine3.21
    container_name: clinic-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_clinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical-clinic

volumes:
  postgres_data:

networks:
  clinic-network:
    driver: bridge